###################################################################

# Created by write_sdc on Tue Dec 24 02:22:43 2024

###################################################################
set sdc_version 2.1

set_units -time ns -resistance 1.000000e+04kOhm -capacitance 1.000000e-04pF    \
-voltage V -current uA
set_load -pin_load 0.05 [get_ports {P[8]}]
set_load -pin_load 0.05 [get_ports {P[7]}]
set_load -pin_load 0.05 [get_ports {P[6]}]
set_load -pin_load 0.05 [get_ports {P[5]}]
set_load -pin_load 0.05 [get_ports {P[4]}]
set_load -pin_load 0.05 [get_ports {P[3]}]
set_load -pin_load 0.05 [get_ports {P[2]}]
set_load -pin_load 0.05 [get_ports {P[1]}]
set_load -pin_load 0.05 [get_ports {P[0]}]
set_ideal_network -no_propagate  [get_ports clk]
create_clock [get_ports clk]  -period 700  -waveform {0 350}
set_input_delay -clock clk  0  [get_ports clk]
set_input_delay -clock clk  0  [get_ports rst_n]
set_input_delay -clock clk  350  [get_ports {T_w1[3]}]
set_input_delay -clock clk  350  [get_ports {T_w1[2]}]
set_input_delay -clock clk  350  [get_ports {T_w1[1]}]
set_input_delay -clock clk  350  [get_ports {T_w1[0]}]
set_input_delay -clock clk  350  [get_ports {T_w2[3]}]
set_input_delay -clock clk  350  [get_ports {T_w2[2]}]
set_input_delay -clock clk  350  [get_ports {T_w2[1]}]
set_input_delay -clock clk  350  [get_ports {T_w2[0]}]
set_input_delay -clock clk  350  [get_ports {T_w3[3]}]
set_input_delay -clock clk  350  [get_ports {T_w3[2]}]
set_input_delay -clock clk  350  [get_ports {T_w3[1]}]
set_input_delay -clock clk  350  [get_ports {T_w3[0]}]
set_input_delay -clock clk  350  [get_ports {T_w4[3]}]
set_input_delay -clock clk  350  [get_ports {T_w4[2]}]
set_input_delay -clock clk  350  [get_ports {T_w4[1]}]
set_input_delay -clock clk  350  [get_ports {T_w4[0]}]
set_input_delay -clock clk  350  [get_ports {T_w5[3]}]
set_input_delay -clock clk  350  [get_ports {T_w5[2]}]
set_input_delay -clock clk  350  [get_ports {T_w5[1]}]
set_input_delay -clock clk  350  [get_ports {T_w5[0]}]
set_input_delay -clock clk  350  [get_ports {T_w6[3]}]
set_input_delay -clock clk  350  [get_ports {T_w6[2]}]
set_input_delay -clock clk  350  [get_ports {T_w6[1]}]
set_input_delay -clock clk  350  [get_ports {T_w6[0]}]
set_input_delay -clock clk  350  [get_ports {T_w7[3]}]
set_input_delay -clock clk  350  [get_ports {T_w7[2]}]
set_input_delay -clock clk  350  [get_ports {T_w7[1]}]
set_input_delay -clock clk  350  [get_ports {T_w7[0]}]
set_input_delay -clock clk  350  [get_ports {T_w8[3]}]
set_input_delay -clock clk  350  [get_ports {T_w8[2]}]
set_input_delay -clock clk  350  [get_ports {T_w8[1]}]
set_input_delay -clock clk  350  [get_ports {T_w8[0]}]
set_input_delay -clock clk  350  [get_ports {T_w9[3]}]
set_input_delay -clock clk  350  [get_ports {T_w9[2]}]
set_input_delay -clock clk  350  [get_ports {T_w9[1]}]
set_input_delay -clock clk  350  [get_ports {T_w9[0]}]
set_input_delay -clock clk  350  [get_ports {T_w10[3]}]
set_input_delay -clock clk  350  [get_ports {T_w10[2]}]
set_input_delay -clock clk  350  [get_ports {T_w10[1]}]
set_input_delay -clock clk  350  [get_ports {T_w10[0]}]
set_input_delay -clock clk  350  [get_ports {T_w11[3]}]
set_input_delay -clock clk  350  [get_ports {T_w11[2]}]
set_input_delay -clock clk  350  [get_ports {T_w11[1]}]
set_input_delay -clock clk  350  [get_ports {T_w11[0]}]
set_input_delay -clock clk  350  [get_ports {T_w12[3]}]
set_input_delay -clock clk  350  [get_ports {T_w12[2]}]
set_input_delay -clock clk  350  [get_ports {T_w12[1]}]
set_input_delay -clock clk  350  [get_ports {T_w12[0]}]
set_input_delay -clock clk  350  [get_ports {T_w13[3]}]
set_input_delay -clock clk  350  [get_ports {T_w13[2]}]
set_input_delay -clock clk  350  [get_ports {T_w13[1]}]
set_input_delay -clock clk  350  [get_ports {T_w13[0]}]
set_input_delay -clock clk  350  [get_ports {T_w14[3]}]
set_input_delay -clock clk  350  [get_ports {T_w14[2]}]
set_input_delay -clock clk  350  [get_ports {T_w14[1]}]
set_input_delay -clock clk  350  [get_ports {T_w14[0]}]
set_input_delay -clock clk  350  [get_ports {T_w15[3]}]
set_input_delay -clock clk  350  [get_ports {T_w15[2]}]
set_input_delay -clock clk  350  [get_ports {T_w15[1]}]
set_input_delay -clock clk  350  [get_ports {T_w15[0]}]
set_input_delay -clock clk  350  [get_ports {T_w16[3]}]
set_input_delay -clock clk  350  [get_ports {T_w16[2]}]
set_input_delay -clock clk  350  [get_ports {T_w16[1]}]
set_input_delay -clock clk  350  [get_ports {T_w16[0]}]
set_input_delay -clock clk  350  [get_ports {T_w17[3]}]
set_input_delay -clock clk  350  [get_ports {T_w17[2]}]
set_input_delay -clock clk  350  [get_ports {T_w17[1]}]
set_input_delay -clock clk  350  [get_ports {T_w17[0]}]
set_input_delay -clock clk  350  [get_ports {T_w18[3]}]
set_input_delay -clock clk  350  [get_ports {T_w18[2]}]
set_input_delay -clock clk  350  [get_ports {T_w18[1]}]
set_input_delay -clock clk  350  [get_ports {T_w18[0]}]
set_input_delay -clock clk  350  [get_ports {T_w19[3]}]
set_input_delay -clock clk  350  [get_ports {T_w19[2]}]
set_input_delay -clock clk  350  [get_ports {T_w19[1]}]
set_input_delay -clock clk  350  [get_ports {T_w19[0]}]
set_input_delay -clock clk  350  [get_ports {T_w20[3]}]
set_input_delay -clock clk  350  [get_ports {T_w20[2]}]
set_input_delay -clock clk  350  [get_ports {T_w20[1]}]
set_input_delay -clock clk  350  [get_ports {T_w20[0]}]
set_input_delay -clock clk  350  [get_ports {T_w21[3]}]
set_input_delay -clock clk  350  [get_ports {T_w21[2]}]
set_input_delay -clock clk  350  [get_ports {T_w21[1]}]
set_input_delay -clock clk  350  [get_ports {T_w21[0]}]
set_input_delay -clock clk  350  [get_ports {T_w22[3]}]
set_input_delay -clock clk  350  [get_ports {T_w22[2]}]
set_input_delay -clock clk  350  [get_ports {T_w22[1]}]
set_input_delay -clock clk  350  [get_ports {T_w22[0]}]
set_input_delay -clock clk  350  [get_ports {T_w23[3]}]
set_input_delay -clock clk  350  [get_ports {T_w23[2]}]
set_input_delay -clock clk  350  [get_ports {T_w23[1]}]
set_input_delay -clock clk  350  [get_ports {T_w23[0]}]
set_input_delay -clock clk  350  [get_ports {T_w24[3]}]
set_input_delay -clock clk  350  [get_ports {T_w24[2]}]
set_input_delay -clock clk  350  [get_ports {T_w24[1]}]
set_input_delay -clock clk  350  [get_ports {T_w24[0]}]
set_input_delay -clock clk  350  [get_ports {T_w25[3]}]
set_input_delay -clock clk  350  [get_ports {T_w25[2]}]
set_input_delay -clock clk  350  [get_ports {T_w25[1]}]
set_input_delay -clock clk  350  [get_ports {T_w25[0]}]
set_input_delay -clock clk  350  [get_ports {T_w26[3]}]
set_input_delay -clock clk  350  [get_ports {T_w26[2]}]
set_input_delay -clock clk  350  [get_ports {T_w26[1]}]
set_input_delay -clock clk  350  [get_ports {T_w26[0]}]
set_input_delay -clock clk  350  [get_ports {T_w27[3]}]
set_input_delay -clock clk  350  [get_ports {T_w27[2]}]
set_input_delay -clock clk  350  [get_ports {T_w27[1]}]
set_input_delay -clock clk  350  [get_ports {T_w27[0]}]
set_input_delay -clock clk  350  [get_ports {T_w28[3]}]
set_input_delay -clock clk  350  [get_ports {T_w28[2]}]
set_input_delay -clock clk  350  [get_ports {T_w28[1]}]
set_input_delay -clock clk  350  [get_ports {T_w28[0]}]
set_input_delay -clock clk  350  [get_ports {T_w29[3]}]
set_input_delay -clock clk  350  [get_ports {T_w29[2]}]
set_input_delay -clock clk  350  [get_ports {T_w29[1]}]
set_input_delay -clock clk  350  [get_ports {T_w29[0]}]
set_input_delay -clock clk  350  [get_ports {T_w30[3]}]
set_input_delay -clock clk  350  [get_ports {T_w30[2]}]
set_input_delay -clock clk  350  [get_ports {T_w30[1]}]
set_input_delay -clock clk  350  [get_ports {T_w30[0]}]
set_input_delay -clock clk  350  [get_ports {T_w31[3]}]
set_input_delay -clock clk  350  [get_ports {T_w31[2]}]
set_input_delay -clock clk  350  [get_ports {T_w31[1]}]
set_input_delay -clock clk  350  [get_ports {T_w31[0]}]
set_input_delay -clock clk  350  [get_ports {T_w32[3]}]
set_input_delay -clock clk  350  [get_ports {T_w32[2]}]
set_input_delay -clock clk  350  [get_ports {T_w32[1]}]
set_input_delay -clock clk  350  [get_ports {T_w32[0]}]
set_output_delay -clock clk  350  [get_ports {P[8]}]
set_output_delay -clock clk  350  [get_ports {P[7]}]
set_output_delay -clock clk  350  [get_ports {P[6]}]
set_output_delay -clock clk  350  [get_ports {P[5]}]
set_output_delay -clock clk  350  [get_ports {P[4]}]
set_output_delay -clock clk  350  [get_ports {P[3]}]
set_output_delay -clock clk  350  [get_ports {P[2]}]
set_output_delay -clock clk  350  [get_ports {P[1]}]
set_output_delay -clock clk  350  [get_ports {P[0]}]
